spring:
  main:
    allow-circular-references: true # 允许循环依赖，因为项目是三层架构，无法避免这个情况。
  cloud:
    # Spring Cloud Gateway 配置项，对应 GatewayProperties 类
    gateway:
      # 路由配置项，对应 RouteDefinition 数组
      routes:
        - # AI模型训练
          - id: model-admin-api
            uri: lb://model-server
            predicates: # 断言，作为路由的匹配条件，对应 RouteDefinition 数组
              - Path=/admin-api/model/**
            filters:
              - StripPrefix=1
              - RewritePath=/admin-api/model/v3/api-docs, /v3/api-docs # 配置，保证转发到 /v3/api-docs
        # 模型实验服务
        - id: studio-admin-api
          uri: lb://studio-server
          predicates: # 断言，作为路由的匹配条件，对应 RouteDefinition 数组
            - Path=/admin-api/experiment/**
          filters:
            - StripPrefix=1
            - RewritePath=/admin-api/dataset/v3/api-docs, /v3/api-docs # 配置，保证转发到 /v3/api-docs
        # 数据集服务
        - id: dataset-admin-api
          uri: lb://dataset-server
          predicates: # 断言，作为路由的匹配条件，对应 RouteDefinition 数组
            - Path=/admin-api/dataset/**, /admin-api/warehouse/**
          filters:
            - StripPrefix=1
            - RewritePath=/admin-api/dataset/v3/api-docs, /v3/api-docs # 配置，保证转发到 /v3/api-docs
        # 文件服务
        - id: file-admin-api
          uri: lb://file-server
          predicates: # 断言，作为路由的匹配条件，对应 RouteDefinition 数组
            - Path=/admin-api/file/**, /admin-api/sysFile/**
          filters:
            - StripPrefix=1
            - RewritePath=/admin-api/device/v3/api-docs, /v3/api-docs # 配置，保证转发到 /v3/api-docs
        # Visualis服务
        - id: visualis-admin-api
          uri: lb://visualis-server
          predicates: # 断言，作为路由的匹配条件，对应 RouteDefinition 数组
            - Path=/admin-api/api/datasource/**,/admin-api/api/file/**,/admin-api/api/project/**,
          filters:
            - StripPrefix=1
            - RewritePath=/admin-api/device/v3/api-docs, /v3/api-docs # 配置，保证转发到 /v3/api-docs
        # Message服务
        - id: message-admin-api
          uri: lb://message-server
          predicates: # 断言，作为路由的匹配条件，对应 RouteDefinition 数组
            - Path=/admin-api/message/**
          filters:
            - StripPrefix=1
            - RewritePath=/admin-api/device/v3/api-docs, /v3/api-docs # 配置，保证转发到 /v3/api-docs
        ## device-server 服务
        - id: device-admin-api # 路由的编号
          uri: lb://device-server
          predicates: # 断言，作为路由的匹配条件，对应 RouteDefinition 数组
            - Path=/admin-api/device/**, /admin-api/product/**, /admin-api/productTemplate/**, /admin-api/ota/**, /admin-api/protocol/**, /admin-api/rule/**, /admin-api/deviceThingModel/**, /admin-api/deviceEvent/**, /admin-api/deviceService/**, /admin-api/shadow/**, /admin-api/topic/**, /admin-api/productProperties/**, /admin-api/productCommands/**, /admin-api/productServices/**, /admin-api/productEvent/**, /admin-api/version/**, /admin-api/packages/**, /admin-api/version/**, /admin-api/api/**, /admin-api/calculate/**
          filters:
            - StripPrefix=1
            - RewritePath=/admin-api/device/v3/api-docs, /v3/api-docs # 配置，保证转发到 /v3/api-docs
        - id: device-app-api # 路由的编号
          uri: lb://device-server
          predicates: # 断言，作为路由的匹配条件，对应 RouteDefinition 数组
            - Path=/app-api/device/**
          filters:
            - StripPrefix=1
            - RewritePath=/admin-api/device/v3/api-docs, /v3/api-docs # 配置，保证转发到 /v3/api-docs
        ## system-server 服务
        - id: system-admin-api # 路由的编号
          uri: lb://system-server
          predicates: # 断言，作为路由的匹配条件，对应 RouteDefinition 数组
            - Path=/admin-api/system/**
          filters:
            - RewritePath=/admin-api/system/v3/api-docs, /v3/api-docs # 配置，保证转发到 /v3/api-docs
        - id: system-app-api # 路由的编号
          uri: lb://system-server
          predicates: # 断言，作为路由的匹配条件，对应 RouteDefinition 数组
            - Path=/app-api/system/**
          filters:
            - RewritePath=/app-api/system/v3/api-docs, /v3/api-docs
        ## infra-server 服务
        - id: infra-admin-api # 路由的编号
          uri: lb://infra-server
          predicates: # 断言，作为路由的匹配条件，对应 RouteDefinition 数组
            - Path=/admin-api/infra/**
          filters:
            - RewritePath=/admin-api/infra/v3/api-docs, /v3/api-docs
        - id: infra-app-api # 路由的编号
          uri: lb://infra-server
          predicates: # 断言，作为路由的匹配条件，对应 RouteDefinition 数组
            - Path=/app-api/infra/**
          filters:
            - RewritePath=/app-api/infra/v3/api-docs, /v3/api-docs
        - id: infra-spring-boot-admin # 路由的编号（Spring Boot Admin）
          uri: lb://infra-server
          predicates: # 断言，作为路由的匹配条件，对应 RouteDefinition 数组
            - Path=/admin/**
        - id: infra-websocket # 路由的编号（WebSocket）
          uri: lb://infra-server
          predicates: # 断言，作为路由的匹配条件，对应 RouteDefinition 数组
            - Path=/infra/ws/**
        # TDengine服务
        - id: iot-modules-tdengine
          uri: lb://tdengine-server
          predicates: # 断言，作为路由的匹配条件，对应 RouteDefinition 数组
            - Path=/admin-api/tdengine/**
          filters:
            - RewritePath=/admin-api/device/v3/api-docs, /v3/api-docs # 配置，保证转发到 /v3/api-docs
        # Broker服务
        - id: iot-modules-broker
          uri: lb://broker-server
          predicates: # 断言，作为路由的匹配条件，对应 RouteDefinition 数组
            - Path=/admin-api/broker/**
          filters:
            - RewritePath=/admin-api/device/v3/api-docs, /v3/api-docs # 配置，保证转发到 /v3/api-docs
      x-forwarded:
        prefix-enabled: false # 避免 Swagger 重复带上额外的 /admin-api/system 前缀

knife4j:
  # 聚合 Swagger 文档，参考 https://doc.xiaominfo.com/docs/action/springcloud-gateway 文档
  gateway:
    enabled: true
    routes:
      - name: system-server
        service-name: system-server
        url: /admin-api/system/v3/api-docs
      - name: infra-server
        service-name: infra-server
        url: /admin-api/infra/v3/api-docs
      - name: device-server
        service-name: device-server
        url: /admin-api/device/v3/api-docs

--- #################### BasicLab相关配置 ####################

iot:
  info:
    version: 1.0.0